### PR TITLE
feat: upgrade to v3

### PR DESCRIPTION
**Pull request by nlewis84**
@vinnyjth This is not ready for primetime, but it does boot up and you can login and see content. Let me know if this is enough for your to test your config stuff.

### CODE REVIEW

**Comment by vinnyjth** [comment]
@nlewis84 I had to copy over some additional changes from core in order to get up and running. Does this work for you?

**Comment by nlewis84** [comment]
@vinnyjth After a `yarn` this ran for me. User Settings modal and Prayer isn't working, but that may not interfere with your testing.

**Comment by nlewis84** [comment]
@vinnyjth I'm using this branch now for an actual upgrade to v3.5.0, so I'm likely going to be breaking stuff. 😬

**Comment by nlewis84** [comment]
https://github.com/ApollosProject/apollos-apps/compare/v2.36.3...v3.5.0

**Comment by nlewis84** [comment]
@vinnyjth There is probably some Open ID setup left to do, but I just left that flow and did regular sign in and this is working for iOS and Android.

**Pull request merged**
